# Generated by Django 3.0.3 on 2020-04-11 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0002_user_payment_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Payment_Details',
        ),
    ]
