# Generated by Django 3.0.3 on 2020-04-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0003_delete_user_payment_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Payment_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('September_05_2019', models.BooleanField(default=False)),
                ('October_05_2019', models.BooleanField(default=False)),
                ('November_05_2019', models.BooleanField(default=False)),
                ('December_05_2019', models.BooleanField(default=False)),
                ('January_05_2020', models.BooleanField(default=False)),
                ('Febuary_05_2020', models.BooleanField(default=False)),
                ('March_05_2020', models.BooleanField(default=False)),
                ('April_05_2020', models.BooleanField(default=False)),
                ('May_05_2020', models.BooleanField(default=False)),
                ('June_05_2020', models.BooleanField(default=False)),
                ('July_05_2020', models.BooleanField(default=False)),
                ('August_05_2020', models.BooleanField(default=False)),
                ('September_05_2020', models.BooleanField(default=False)),
                ('October_05_2020', models.BooleanField(default=False)),
                ('November_05_2020', models.BooleanField(default=False)),
                ('December_05_2020', models.BooleanField(default=False)),
                ('January_05_2021', models.BooleanField(default=False)),
                ('Febuary_05_2021', models.BooleanField(default=False)),
                ('March_05_2021', models.BooleanField(default=False)),
                ('April_05_2021', models.BooleanField(default=False)),
                ('May_05_2021', models.BooleanField(default=False)),
            ],
        ),
    ]
