# Generated by Django 3.0.3 on 2020-04-11 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0005_auto_20200411_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_payment_details',
            old_name='Febuary_05_2021',
            new_name='February_05_2021',
        ),
    ]
