# Generated by Django 3.0.3 on 2020-04-15 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0006_auto_20200411_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_payment_details',
            old_name='name',
            new_name='customer_name',
        ),
    ]
