# Generated by Django 3.0.3 on 2020-04-15 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0008_auto_20200415_1638'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Payment_Details',
        ),
    ]
