# Generated by Django 3.0.3 on 2020-04-19 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0010_user_payment_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_payment_details',
            old_name='August_05_2019',
            new_name='April_05_2021',
        ),
        migrations.RenameField(
            model_name='user_payment_details',
            old_name='February_05_2020',
            new_name='February_05_2021',
        ),
        migrations.RenameField(
            model_name='user_payment_details',
            old_name='July_05_2019',
            new_name='February_05_2029',
        ),
        migrations.RenameField(
            model_name='user_payment_details',
            old_name='June_05_2019',
            new_name='January_05_2021',
        ),
        migrations.RenameField(
            model_name='user_payment_details',
            old_name='May_05_2019',
            new_name='March_05_2021',
        ),
        migrations.RemoveField(
            model_name='user_payment_details',
            name='September_05_2019',
        ),
    ]
