# Generated by Django 3.0.3 on 2020-04-19 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0011_auto_20200419_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_payment_details',
            old_name='February_05_2029',
            new_name='February_05_2020',
        ),
    ]
