# Generated by Django 3.0.3 on 2020-04-19 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0013_user_payment_details_september_05_2019'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Payment_Details',
        ),
    ]
