# Generated by Django 3.0.3 on 2020-04-19 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0017_user_payment_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Chit_Draw_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('customer_name', models.CharField(max_length=100)),
                ('no_of_chits', models.IntegerField()),
                ('month_of_bid', models.IntegerField()),
                ('total_chit_amount_transferable', models.IntegerField()),
                ('commission_amount', models.IntegerField()),
                ('respective_chit_amount', models.IntegerField()),
                ('total_received', models.IntegerField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_details.User_Payment_Details')),
            ],
        ),
    ]
