# Generated by Django 3.0.3 on 2020-04-19 17:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0018_user_chit_draw_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_chit_draw_details',
            name='note',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
