# Generated by Django 3.0.3 on 2020-04-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0019_user_chit_draw_details_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_chit_draw_details',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
