# Generated by Django 3.0.3 on 2020-04-20 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0020_auto_20200420_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_chit_draw_details',
            name='note',
        ),
        migrations.AddField(
            model_name='user_chit_draw_details',
            name='admin_note',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_chit_draw_details',
            name='customer_note',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
