# Generated by Django 3.0.3 on 2020-04-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0021_auto_20200420_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_chit_draw_details',
            name='no_of_chits',
        ),
        migrations.AlterField(
            model_name='user_chit_draw_details',
            name='month_of_bid',
            field=models.CharField(max_length=200),
        ),
    ]
