# Generated by Django 3.0.3 on 2020-04-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0022_auto_20200421_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monthly_Bid_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('no_of_chits', models.IntegerField()),
                ('bid_month', models.IntegerField()),
                ('total_chit_amount', models.IntegerField()),
                ('total_commission_amount', models.IntegerField()),
                ('amount_to_pay', models.IntegerField()),
                ('commission_amount', models.IntegerField()),
                ('total_amount_to_pay', models.IntegerField()),
            ],
        ),
    ]
