# Generated by Django 3.0.3 on 2020-04-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0024_remove_monthly_bid_details_no_of_chits'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthly_bid_details',
            name='no_of_chits',
            field=models.IntegerField(default=1),
        ),
    ]
