# Generated by Django 3.0.3 on 2020-04-15 10:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chit_registration', '0002_auto_20200410_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration_chit',
            old_name='name',
            new_name='customer_name',
        ),
        migrations.AddField(
            model_name='registration_chit',
            name='group_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
